spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: aaa
    password: aaa
    platform: h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

logging:
  file: E:\log\familynote.log
  level:
#    org:
#      hibernate: debug
    root: info
